### ISSUE TITLE
About using for arbitrary dimensions

### ISSUE THREAD

**Issue by kongdebug** [yqthanks/significantDBSCAN#1]
Thank you very much for your work.  Now I need to deal with 3 dimensional data, how should I modify the code？

**Comment by yqthanks** [comment]
Hi @kongdebug, the python version (https://github.com/yqthanks/Significant-DBSCAN-python) is a multi-dimensional implementation (without the acceleration) and please check it out to see if it fits your data. For the matlab version, the default 2D should have been used in a grid-index (for querying neighbor points), the grid-based acceleration and distance calculation between points. If you modify or take out the grid-related accelerations, and update the distance calculation parts, it should work. We will consider updating the matlab version later for multi-dimensional data. Thanks for checking this.

**Comment by kongdebug** [comment]
> Hi @kongdebug, the python version (https://github.com/yqthanks/Significant-DBSCAN-python) is a multi-dimensional implementation (without the acceleration) and please check it out to see if it fits your data. For the matlab version, the default 2D should have been used in a grid-index (for querying neighbor points), the grid-based acceleration and distance calculation between points. If you modify or take out the grid-related accelerations, and update the distance calculation parts, it should work. We will consider updating the matlab version later for multi-dimensional data. Thanks for checking this.

Thank you for your reply. The python version repo (https://github.com/yqthanks/Significant-DBSCAN-python) is useful!
